theme = "github_dark"


[editor]
auto-save = true
idle-timeout=100
color-modes=true

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[editor.inline-diagnostics]
# inline diagnostics for severity >= "error"
cursor-line = "error"

[keys.normal]
G = "goto_file_end"

[keys.normal.g]
q = ":reflow"

